# Variables and Arrays

In [1]:
from random import random
import numpy as np
import torch

### Comments

In [2]:
# this is a comment

In [3]:
"""
    this is a docstring
    for testing
"""

def my_function():
    """ Here is a docstring inside a function """

In [4]:
my_function.__doc__

' Here is a docstring inside a function '

## Variables

In [6]:
# integer
a = 25

In [7]:
# Float
b = 11.39

In [8]:
# string
ticker = "ETH"

In [9]:
# Boolean
is_profit = True

## Opeators and Expressions

In [10]:
c = a + b
print(c)

36.39


In [11]:
c = a - b
print(c)

13.61


In [12]:
c = a * b
print(c)

284.75


In [13]:
c = a / b
print(c)

2.194907813871817


In [14]:
c = a % b
print(c)

2.219999999999999


## String Manipulation

In [26]:
# starts with
text = "abc"
 
# returns True
result = text.startswith('ab')
print(result)

True


In [27]:
# replace
string = "abc"
 
# Prints the string by replacing
print(string.replace("a", "b"))

bbc


In [28]:
string = "abcde"
first_characters = string[0: 3]
print("First 3 characters:", first_characters)

First 3 characters: abc


## Lists and Arrays

In [15]:
# Flexible and easy to work with
# I can add strings here if I wanted
prices_list = [2.34, 0.21, 5.89, 2.98, "BTC"]
print(prices_list)

[2.34, 0.21, 5.89, 2.98, 'BTC']


In [16]:
# arrays are better for heavy computantions and are faster, only one type of data
prices_array = np.array([2.34, 0.21, 5.89, 2.98])
print(prices_array)

[2.34 0.21 5.89 2.98]


In [17]:
# For Neural Networks (how we feed the data into the tensor)
prices_tensor = torch.Tensor(prices_array)
print(prices_tensor)

tensor([2.3400, 0.2100, 5.8900, 2.9800])


In [18]:
# append to the list
prices_list.append(4.92)
print(prices_list)

[2.34, 0.21, 5.89, 2.98, 'BTC', 4.92]


In [19]:
# Call items
first_item = prices_list[0]
print(first_item)

2.34


In [20]:
# call item (last element)
last_item = prices_list[-1]
print(last_item)

4.92


In [21]:
# call the first two items
first_two_items = prices_list[:2]
# call all items but the last one
all_but_last = prices_list[:-1]
print(first_two_items)
print(all_but_last)

[2.34, 0.21]
[2.34, 0.21, 5.89, 2.98, 'BTC']


In [22]:
# Lengths
list_length = len(prices_list)
print("list length: ", list_length)
arr_length = len(prices_array)
print("array length: ", arr_length)
tensor_length = len(prices_tensor)
print("tensor length: ", tensor_length)

list length:  6
array length:  4
tensor length:  4


In [23]:
# Shapes
# opening an array within an array
open_prices = [1.34, 0.22, 1.19, 0.31]
close_prices = [1.37, 2.00, 0.17, 2.22]
prices_arr = np.array([open_prices, close_prices])
print(prices_arr)
print(f"Prices Shape: {prices_arr.shape}")

[[1.34 0.22 1.19 0.31]
 [1.37 2.   0.17 2.22]]
Prices Shape: (2, 4)


In [24]:
# Reshape array
reshaped = prices_arr.reshape(4, 2)
print(reshaped)
#it has reshaped them into 4 arrays of 2

[[1.34 0.22]
 [1.19 0.31]
 [1.37 2.  ]
 [0.17 2.22]]


In [25]:
# Flatten an array, [:] means all items, and then get the first item
flatten = prices_arr.reshape(1,8)[:][0]
print(flatten)

[1.34 0.22 1.19 0.31 1.37 2.   0.17 2.22]
